// Generated by CoffeeScript 1.6.2
(function() {
  var server;

  server = require('http').createServer(function(request, response) {
    response.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return response.end('Hello Worldsies');
  });

  server.listen(8124);

  console.log('Server running at http://127.0.0.1:8124/');

}).call(this);
